/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 100-lc.glb --transform --instanceall -j -k 
Files: 100-lc.glb [13.4MB] > /Users/williamfulton/Desktop/100-lc-transformed.glb [1.83MB] (86%)
*/

import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = React.createContext()

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/100-lc-transformed.glb')
  const instances = React.useMemo(
    () => ({
      Object: nodes.Object_6,
      Object1: nodes.Object_10,
      Object2: nodes.Object_13,
      Frontbumper: nodes['front-bumper'],
      Object3: nodes.Object_19,
      Bumperlight: nodes['bumper-light001'],
      Object4: nodes.Object_25,
      Object5: nodes.Object_28,
      Object6: nodes.Object_29,
      Object7: nodes.Object_35,
      Passengerrearrim: nodes['passenger-rear-rim'],
      Passengerreartire: nodes['passenger-rear-tire'],
      Frontlefttire: nodes['front-left-tire'],
      Driverfrontrim: nodes['driver-front-rim'],
      Object8: nodes.Object_41,
      Driverreartire: nodes['driver-rear-tire'],
      Driverrearrim: nodes['driver-rear-rim'],
      Object9: nodes.Object_47,
      Object10: nodes.Object_53,
      Passengerfrontrim: nodes['passenger-front-rim'],
      Passengerronttire: nodes['passenger-ront-tire'],
      Body: nodes.body,
      Frontbodypanel: nodes['front-body-panel'],
      Object11: nodes.Object_59,
      Object12: nodes.Object_60,
      Bottomtrim: nodes['bottom-trim'],
      Object13: nodes.Object_64,
      Rearvents: nodes['rear-vents'],
      Roofrack: nodes['roof-rack'],
      Object14: nodes.Object_70,
      Object15: nodes.Object_72,
      Driverfrontsecondrowtrim: nodes['driver-front-second-row-trim'],
      Driverfrontsecondrowtrim1: nodes['driver-front-second-row-trim001'],
      Driverrearsecondrowtrim: nodes['driver-rear-second-row-trim'],
      Driverrearsecondrowtrim1: nodes['driver-rear-second-row-trim001'],
      Object16: nodes.Object_75,
      Outsidewindshieldtrim: nodes['outside-windshield-trim'],
      Driversecondrowwindow: nodes['driver-second-row-window'],
      Object17: nodes.Object_77,
      Passengersecondrowwindow: nodes['passenger-second-row-window'],
      Windshield: nodes.windshield001,
      Object18: nodes.Object_83,
      Object19: nodes.Object_85,
      Object20: nodes.Object_88,
      Object21: nodes.Object_89,
      Object22: nodes.Object_92,
      Object23: nodes.Object_93,
      Object24: nodes.Object_94,
      Object25: nodes.Object_95,
      Object26: nodes.Object_100,
      Object27: nodes.Object_99,
      Object28: nodes.Object_102,
      Object29: nodes.Object_104,
      Object30: nodes.Object_105,
      Object31: nodes.Object_107,
      Object32: nodes.Object_108,
      Object33: nodes.Object_110,
      Object34: nodes.Object_111,
      Object35: nodes.Object_113,
      Object36: nodes.Object_114,
      Object37: nodes.Object_116,
      Object38: nodes.Object_118,
      Object39: nodes.Object_120,
      Object40: nodes.Object_121,
      Object41: nodes.Object_124,
      Object42: nodes.Object_125,
      Object43: nodes.Object_128,
      Object44: nodes.Object_130,
      Object45: nodes.Object_133,
      Object46: nodes.Object_134,
      Insideuppertrim: nodes['inside-upper-trim'],
      Object47: nodes.Object_138,
      Object48: nodes.Object_139,
      Cabinterior: nodes['cab-interior'],
      Windowtrim: nodes['window-trim'],
      Object49: nodes.Object_148,
      Object50: nodes.Object_154,
      Object51: nodes.Object_155,
      Object52: nodes.Object_156,
      Object53: nodes.Object_158,
      Object54: nodes.Object_159,
      Object55: nodes.Object_162,
      Object56: nodes.Object_163,
      Object57: nodes.Object_167,
      Object58: nodes.Object_168,
      Passengerhandle: nodes['passenger-handle'],
      Passengerupperpanel: nodes['passenger-upper-panel'],
      Object59: nodes.Object_172,
      Object60: nodes.Object_173,
      Passengerbottompanel: nodes['passenger-bottom-panel'],
      Passengertrim: nodes['passenger-trim'],
      Passengerwindow: nodes['passenger-window'],
      Driverbottompanel: nodes['driver-bottom-panel'],
      Driverglass: nodes['driver-glass'],
      Leftmirror: nodes['left-mirror'],
      Leftmirror1: nodes['left-mirror001'],
      Object61: nodes.Object_177,
      Frontlefthandle: nodes['front-left-handle'],
      Object62: nodes.Object_183,
      Object63: nodes.Object_184,
      Object64: nodes.Object_185,
      Driverdoor: nodes['driver-door'],
      Object65: nodes.Object_187,
      Object66: nodes.Object_191,
      Object67: nodes.Object_192,
      Driverpanel: nodes['driver-panel'],
      Object68: nodes.Object_196,
      Object69: nodes.Object_197,
      Leftmidtrim: nodes['left-mid-trim'],
      Object70: nodes.Object_201,
      Object71: nodes.Object_202,
      Object72: nodes.Object_206,
      Object73: nodes.Object_209,
      Passengerreardoorhandle: nodes['passenger-rear-door-handle'],
      Object74: nodes.Object_212,
      Passengerreardoor: nodes['passenger-rear-door'],
      Object75: nodes.Object_217,
      Passengerrearhandle: nodes['passenger-rear-handle'],
      Object76: nodes.Object_221,
      Object77: nodes.Object_222,
      Passengerbottompanel1: nodes['passenger-bottom-panel001'],
      Passengerreartrim: nodes['passenger-rear-trim'],
      Passengerrearwindow: nodes['passenger-rear-window'],
      Driverrearbottompanel: nodes['driver-rear-bottom-panel'],
      Driverreartrim: nodes['driver-rear-trim'],
      Driverrearwindow: nodes['driver-rear-window'],
      Object78: nodes.Object_226,
      Driverreardoorhandle: nodes['driver-rear-door-handle'],
      Object79: nodes.Object_229,
      Driverreardoor: nodes['driver-rear-door'],
      Object80: nodes.Object_232,
      Driverrearhandle: nodes['driver-rear-handle'],
      Driverreartoppanel: nodes['driver-rear-top-panel'],
      Object81: nodes.Object_237,
      Object82: nodes.Object_241,
      Object83: nodes.Object_242,
      Object84: nodes.Object_262,
      Hood: nodes.hood,
      Object85: nodes.Object_263,
      Grill: nodes.grill,
      Object86: nodes.Object_249,
      Object87: nodes.Object_252,
      Object88: nodes.Object_255,
      Object89: nodes.Object_256,
      Object90: nodes.Object_257,
      Object91: nodes.Object_258,
      Driverrunninglight: nodes['driver-running-light'],
      Frontlefttrim: nodes['front-left-trim'],
      Frontleftbottompanel: nodes['front-left-bottom-panel'],
      Object92: nodes.Object_267,
      Object93: nodes.Object_271,
      Object94: nodes.Object_273,
      Leftblinker: nodes['left-blinker001'],
      Leftheadlight: nodes['left-headlight'],
      Object95: nodes.Object_279,
      Passengerfrontbottompanel: nodes['passenger-front-bottom-panel'],
      Object96: nodes.Object_283,
      Passengerfrontupperpanel: nodes['passenger-front-upper-panel001'],
      Passengerfrontupperpanel1: nodes['passenger-front-upper-panel002'],
      Object97: nodes.Object_285,
      Passengerfronttrim: nodes['passenger-front-trim'],
      Passengerrunninglight: nodes['passenger-running-light'],
      Rightblinker: nodes['right-blinker'],
      Rightheadlight: nodes['right-headlight'],
      Frame: nodes.frame,
      Object98: nodes.Object_292,
      Exhaust: nodes.exhaust,
      Enginedrivetrain: nodes['engine-drivetrain'],
      Reardiffaxle: nodes['rear-diff-axle'],
      Object99: nodes.Object_302,
      Object100: nodes.Object_304,
      Object101: nodes.Object_306,
      Object102: nodes.Object_186001,
      Object103: nodes.Object_186001_1,
      Object104: nodes.Object_186001_2,
      Object105: nodes.Object_309,
      Object106: nodes.Object_312,
      Backupperlight: nodes['back-upper-light'],
      Object107: nodes.Object_316,
      Tailgatetrim: nodes['tailgate-trim'],
      Object108: nodes.Object_321,
      Object109: nodes.Object_192_1,
      Object110: nodes.Object_192_2,
      Lowertailgate: nodes['lower-tailgate'],
      Object111: nodes.Object_328,
      Rearwindow: nodes['rear-window'],
      Rearwindowtrim: nodes['rear-window-trim'],
      Uppertailgate: nodes['upper-tailgate'],
      Bumpertrim: nodes['bumper-trim'],
      Object112: nodes.Object_332,
      Rearbumper: nodes['rear-bumper'],
      Bumperlight1: nodes['bumper-light'],
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Object name="Object_6" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object1 name="Object_10" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object2 name="Object_13" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Frontbumper name="front-bumper" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object3 name="Object_19" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Bumperlight name="bumper-light001" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object4 name="Object_25" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object5 name="Object_28" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object6 name="Object_29" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object7 name="Object_35" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerrearrim name="passenger-rear-rim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerreartire name="passenger-rear-tire" position={[0.591, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]} />
      <instances.Frontlefttire name="front-left-tire" position={[4.142, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]} />
      <instances.Driverfrontrim name="driver-front-rim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object8 name="Object_41" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverreartire name="driver-rear-tire" position={[4.131, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]} />
      <instances.Driverrearrim name="driver-rear-rim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object9 name="Object_47" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object10 name="Object_53" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerfrontrim name="passenger-front-rim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerronttire name="passenger-ront-tire" position={[0.592, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]} />
      <instances.Body name="body" position={[0, 0, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Frontbodypanel name="front-body-panel" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object11 name="Object_59" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object12 name="Object_60" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Bottomtrim name="bottom-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object13 name="Object_64" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Rearvents name="rear-vents" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Roofrack name="roof-rack" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object14 name="Object_70" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object15 name="Object_72" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverfrontsecondrowtrim name="driver-front-second-row-trim" position={[0, 0.007, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverfrontsecondrowtrim1 name="driver-front-second-row-trim001" position={[0, -0.003, 0.004]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverrearsecondrowtrim name="driver-rear-second-row-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverrearsecondrowtrim1 name="driver-rear-second-row-trim001" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object16 name="Object_75" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Outsidewindshieldtrim name="outside-windshield-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driversecondrowwindow name="driver-second-row-window" position={[0.008, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object17 name="Object_77" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengersecondrowwindow name="passenger-second-row-window" position={[-0.013, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Windshield name="windshield001" position={[0.001, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object18 name="Object_83" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object19 name="Object_85" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object20 name="Object_88" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object21 name="Object_89" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object22 name="Object_92" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object23 name="Object_93" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object24 name="Object_94" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object25 name="Object_95" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object26 name="Object_100" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object27 name="Object_99" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object28 name="Object_102" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object29 name="Object_104" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object30 name="Object_105" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object31 name="Object_107" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object32 name="Object_108" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object33 name="Object_110" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object34 name="Object_111" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object35 name="Object_113" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object36 name="Object_114" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object37 name="Object_116" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object38 name="Object_118" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object39 name="Object_120" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object40 name="Object_121" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object41 name="Object_124" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object42 name="Object_125" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object43 name="Object_128" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object44 name="Object_130" position={[0.002, 0, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object45 name="Object_133" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object46 name="Object_134" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Insideuppertrim name="inside-upper-trim" position={[0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object47 name="Object_138" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object48 name="Object_139" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Cabinterior name="cab-interior" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Windowtrim name="window-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object49 name="Object_148" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object50 name="Object_154" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object51 name="Object_155" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object52 name="Object_156" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object53 name="Object_158" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object54 name="Object_159" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object55 name="Object_162" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object56 name="Object_163" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object57 name="Object_167" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object58 name="Object_168" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerhandle name="passenger-handle" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerupperpanel name="passenger-upper-panel" position={[-0.004, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object59 name="Object_172" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object60 name="Object_173" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerbottompanel name="passenger-bottom-panel" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengertrim name="passenger-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerwindow name="passenger-window" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverbottompanel name="driver-bottom-panel" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverglass name="driver-glass" position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Leftmirror name="left-mirror" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Leftmirror name="left-mirror002" position={[2.388, -0.003, 0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]} />
      <instances.Leftmirror1 name="left-mirror001" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Leftmirror1 name="left-mirror003" position={[2.386, -0.003, 0.011]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]} />
      <instances.Object61 name="Object_177" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Frontlefthandle name="front-left-handle" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object62 name="Object_183" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object63 name="Object_184" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object64 name="Object_185" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverdoor name="driver-door" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object65 name="Object_187" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object66 name="Object_191" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object67 name="Object_192" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverpanel name="driver-panel" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object68 name="Object_196" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object69 name="Object_197" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Leftmidtrim name="left-mid-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object70 name="Object_201" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object71 name="Object_202" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object72 name="Object_206" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object73 name="Object_209" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerreardoorhandle name="passenger-rear-door-handle" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object74 name="Object_212" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerreardoor name="passenger-rear-door" position={[-0.005, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object75 name="Object_217" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerrearhandle name="passenger-rear-handle" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object76 name="Object_221" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object77 name="Object_222" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerbottompanel1 name="passenger-bottom-panel001" position={[-0.009, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerreartrim name="passenger-rear-trim" position={[-0.011, 0.003, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerrearwindow name="passenger-rear-window" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverrearbottompanel name="driver-rear-bottom-panel" position={[0.01, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverreartrim name="driver-rear-trim" position={[0.007, 0.006, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverrearwindow name="driver-rear-window" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object78 name="Object_226" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverreardoorhandle name="driver-rear-door-handle" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object79 name="Object_229" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverreardoor name="driver-rear-door" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object80 name="Object_232" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverrearhandle name="driver-rear-handle" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverreartoppanel name="driver-rear-top-panel" position={[-0.012, 0.006, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverreartoppanel name="driver-rear-top-panel001" position={[2.396, 0.008, -0.006]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]} />
      <instances.Object81 name="Object_237" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object82 name="Object_241" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object83 name="Object_242" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object84 name="Object_262" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Hood name="hood" position={[0.003, 0.101, -0.028]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.011, 0.01, 0.01]} />
      <instances.Object85 name="Object_263" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Grill name="grill" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object86 name="Object_249" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object87 name="Object_252" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object88 name="Object_255" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object89 name="Object_256" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object90 name="Object_257" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object91 name="Object_258" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Driverrunninglight name="driver-running-light" position={[-0.002, 0, 0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Frontlefttrim name="front-left-trim" position={[0.01, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Frontleftbottompanel name="front-left-bottom-panel" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object92 name="Object_267" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object93 name="Object_271" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object94 name="Object_273" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Leftblinker name="left-blinker001" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Leftheadlight name="left-headlight" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object95 name="Object_279" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerfrontbottompanel name="passenger-front-bottom-panel" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object96 name="Object_283" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerfrontupperpanel name="passenger-front-upper-panel001" position={[2.382, -0.01, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]} />
      <instances.Passengerfrontupperpanel1 name="passenger-front-upper-panel002" position={[0.001, -0.009, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object97 name="Object_285" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerfronttrim name="passenger-front-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Passengerrunninglight name="passenger-running-light" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Rightblinker name="right-blinker" position={[0.003, -0.005, -0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Rightheadlight name="right-headlight" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Frame name="frame" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object98 name="Object_292" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Exhaust name="exhaust" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Enginedrivetrain name="engine-drivetrain" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Reardiffaxle name="rear-diff-axle" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object99 name="Object_302" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object100 name="Object_304" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object101 name="Object_306" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <group name="driver-rear-taillight" rotation={[-Math.PI / 2, 0, 0]} scale={0.011}>
        <instances.Object102 name="Object_186001" />
        <instances.Object103 name="Object_186001_1" />
        <instances.Object104 name="Object_186001_2" />
      </group>
      <group name="driver-rear-taillight001" position={[2.381, 0.006, 0.006]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.011, 0.011, 0.011]}>
        <instances.Object102 name="Object_186001" />
        <instances.Object103 name="Object_186001_1" />
        <instances.Object104 name="Object_186001_2" />
      </group>
      <instances.Object105 name="Object_309" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object106 name="Object_312" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Backupperlight name="back-upper-light" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object107 name="Object_316" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Tailgatetrim name="tailgate-trim" position={[-0.001, 0, 0.015]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object108 name="Object_321" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <group name="rear-wiper" rotation={[-Math.PI / 2, 0, 0]} scale={0.011}>
        <instances.Object109 name="Object_192_1" />
        <instances.Object110 name="Object_192_2" />
      </group>
      <instances.Lowertailgate name="lower-tailgate" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object111 name="Object_328" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Rearwindow name="rear-window" position={[-0.004, 0, 0.013]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Rearwindowtrim name="rear-window-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Uppertailgate name="upper-tailgate" position={[0, 0, 0.016]} rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Bumpertrim name="bumper-trim" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Object112 name="Object_332" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Rearbumper name="rear-bumper" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
      <instances.Bumperlight1 name="bumper-light" rotation={[-Math.PI / 2, 0, 0]} scale={0.011} />
    </group>
  )
}

useGLTF.preload('/100-lc-transformed.glb')
