/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 toyota_land_cruiser_100_series.glb --transform 
Files: toyota_land_cruiser_100_series.glb [7.1MB] > /Users/williamfulton/Desktop/Personal-Projects/landcruiser-viz/public/toyota_land_cruiser_100_series-transformed.glb [362.54KB] (95%)
Author: mavogen1 (https://sketchfab.com/mavogen1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toyota-land-cruiser-100-series-8c6e399714754b31b2bc5208c926204a
Title: Toyota Land Cruiser 100 series
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/toyota_land_cruiser_100_series.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.Foregrou}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.Color_M0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Color_01}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_17.geometry}
        material={materials.Color_D0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.Color_03}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.Color_02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_37.geometry}
        material={materials.vehicle}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.Mirror_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_79.geometry}
        material={materials.chrome}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_65.geometry}
        material={materials.Vehicle}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials.Plastic}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_78.geometry}
        material={materials.Glass_ve}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_94.geometry}
        material={materials.leather}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_121.geometry}
        material={materials.mirror}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_114.geometry}
        material={materials.leathe02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_128.geometry}
        material={materials.Vehicl01}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_141.geometry}
        material={materials.leathe01}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_262.geometry}
        material={materials.Vehicl04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_274.geometry}
        material={materials.Vehicl03}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_276.geometry}
        material={materials.Vehicl02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_273.geometry}
        material={materials.Bohlam_e}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_294.geometry}
        material={materials.Vehicl05}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_313.geometry}
        material={materials.Vehicl06}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/toyota_land_cruiser_100_series-transformed.glb");
