import { SidebarProvider, SidebarTrigger } from "@/ui/sidebar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ActionsMenuBar } from "./components/ActionsMenuBar";
import { AppSidebar } from "./components/Sidebar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "100 Series Visualizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider defaultOpen={true}>
          <AppSidebar />
          <main className="relative w-full max-w-full">
            <nav className="header absolute right-0 top-0 z-50 flex w-full items-center justify-between gap-2 bg-transparent p-2">
              <div className="flex items-center justify-start gap-2">
                <SidebarTrigger className="" />
                {/* <Separator orientation="vertical" className="h-[15px] bg-secondary" />
                <span className="headerText">Toyota Land Cruiser 100 Series</span>
                <Separator orientation="vertical" className="h-[15px] bg-secondary" />
                <span className="headerText">UZJ100L-GNPEKA</span> */}
                <ActionsMenuBar />
              </div>
            </nav>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
