export interface PartNumberDatum {
  partNumber: string;
  keys: string[];
  label: string;
}

export const PartNumberData: PartNumberDatum[] = [
  {
    partNumber: "front-bumper",
    keys: ["Object3", "Object4", "Object5", "Object6"],
    label: "Front Bumper",
  },
  { partNumber: "Body", keys: ["Body"], label: "Body" },
  { partNumber: "Passengerfrontrim", keys: ["Passengerfrontrim"], label: "Passenger Front Rim" },
  { partNumber: "Passengerronttire", keys: ["Passengerronttire"], label: "Passenger Front Tire" },
  { partNumber: "Passengerrearrim", keys: ["Passengerrearrim"], label: "Passenger Rear Rim" },
  { partNumber: "Passengerreartire", keys: ["Passengerreartire"], label: "Passenger Rear Tire" },
  { partNumber: "Frontlefttire", keys: ["Frontlefttire"], label: "Driver Front Tire" },
  { partNumber: "Driverfrontrim", keys: ["Driverfrontrim"], label: "Driver Front Rim" },
  { partNumber: "Driverreartire", keys: ["Driverreartire"], label: "Driver Rear Tire" },
  { partNumber: "Driverrearrim", keys: ["Driverrearrim"], label: "Driver Rear Rim" },
  { partNumber: "Bottomtrim", keys: ["Bottomtrim"], label: "Bottom Trim" },
  { partNumber: "Rearvents", keys: ["Rearvents"], label: "Rear Vents" },
  { partNumber: "Roofrack", keys: ["Roofrack"], label: "Roof rack" },
  { partNumber: "Miscreartrim", keys: ["Miscreartrim"], label: "Misc Rear Trim" },
  { partNumber: "Windshield", keys: ["Windshield"], label: "Windshield" },
  { partNumber: "Windowtrim", keys: ["Windowtrim"], label: "Window Trim" },
  { partNumber: "Passengermirror", keys: ["Passengermirror"], label: "Passenger Mirror" },
  { partNumber: "Passengerhandle", keys: ["Passengerhandle"], label: "Passenger Door Handle" },
  {
    partNumber: "Passengerupperpanel",
    keys: ["Passengerupperpanel"],
    label: "Passenger Upper Panel",
  },
  {
    partNumber: "Passengerbottompanel",
    keys: ["Passengerbottompanel"],
    label: "Passenger Bottom Panel",
  },
  { partNumber: "Passengertrim", keys: ["Passengertrim"], label: "Passenger Trim" },
  { partNumber: "Passengerwindow", keys: ["Passengerwindow"], label: "Passenger Window" },
  { partNumber: "Driverbottompanel", keys: ["Driverbottompanel"], label: "Driver Bottom Panel" },
  { partNumber: "Driverglass", keys: ["Driverglass"], label: "Driver Window" },
  { partNumber: "Leftmirror", keys: ["Leftmirror"], label: "Driver Mirror" },
  { partNumber: "Frontlefthandle", keys: ["Frontlefthandle"], label: "Driver Door Handle" },
  { partNumber: "Leftmidtrim", keys: ["Leftmidtrim"], label: "Driver Mid Trim" },
  { partNumber: "Driverdoor", keys: ["Driverdoor"], label: "Driver Door" },
  { partNumber: "Driverpanel", keys: ["Driverpanel"], label: "Driver Panel" },
  { partNumber: "Passengerreardoor", keys: ["Passengerreardoor"], label: "Passenger Rear Door" },
  {
    partNumber: "Passengerrearhandle",
    keys: ["Passengerrearhandle"],
    label: "Passenger Rear Door Handle",
  },
  {
    partNumber: "Passengerrearpanel",
    keys: ["Passengerrearpanel"],
    label: "Passenger Rear Door Panel",
  },
  {
    partNumber: "Passengerbottompanel1",
    keys: ["Passengerbottompanel1"],
    label: "Passenger Bottom Door Panel",
  },
  { partNumber: "Passengerreartrim", keys: ["Passengerreartrim"], label: "Passenger Rear Trim" },
  {
    partNumber: "Passengerrearwindow",
    keys: ["Passengerrearwindow"],
    label: "Passenger Rear Window",
  },
  {
    partNumber: "Driverrearbottompanel",
    keys: ["Driverrearbottompanel"],
    label: "Driver Rear Bottom Door Panel",
  },
  { partNumber: "Driverreartrim", keys: ["Driverreartrim"], label: "Driver Rear Trim" },
  { partNumber: "Driverreardoor", keys: ["Driverreardoor"], label: "Driver Rear Door" },
  { partNumber: "Driverrearhandle", keys: ["Driverrearhandle"], label: "Driver Rear Door Handle" },
  {
    partNumber: "Driverreartoppanel",
    keys: ["Driverreartoppanel"],
    label: "Driver Rear Top Door Panel",
  },
  { partNumber: "Hood", keys: ["Hood"], label: "Hood" },
  { partNumber: "Grill", keys: ["Object99", "Object100"], label: "Grill" },
  { partNumber: "Driverrearwindow", keys: ["Driverrearwindow"], label: "Driver Rear Window" },
  { partNumber: "Frontlefttrim", keys: ["Frontlefttrim"], label: "Driver Front Trim" },
  {
    partNumber: "Frontleftbottompanel",
    keys: ["Frontleftbottompanel"],
    label: "Driver Bottom Door Panel",
  },
  { partNumber: "Frontleftpanel", keys: ["Frontleftpanel"], label: "Driver Door Panel" },
  { partNumber: "Leftblinker", keys: ["Leftblinker"], label: "Driver Blinker" },
  { partNumber: "Leftheadlight", keys: ["Leftheadlight"], label: "Driver Headlight" },
  {
    partNumber: "Passengerfrontbottompanel",
    keys: ["Passengerfrontbottompanel"],
    label: "Passenger Bottom Door Panel",
  },
  {
    partNumber: "Passengerfrontupperpanel",
    keys: ["Passengerfrontupperpanel"],
    label: "Passenger Upper Door Panel",
  },
  { partNumber: "Passengerfronttrim", keys: ["Passengerfronttrim"], label: "Passenger Door Trim" },
  { partNumber: "Rightblinker", keys: ["Rightblinker"], label: "Passenger Blinker" },
  { partNumber: "Rightheadlight", keys: ["Rightheadlight"], label: "Passenger Headlight" },
  { partNumber: "Exhaust", keys: ["Exhaust"], label: "Exhaust" },
  { partNumber: "Enginedrivetrain", keys: ["Enginedrivetrain"], label: "Engine and Drivetrain" },
  { partNumber: "Reardiffaxle", keys: ["Reardiffaxle"], label: "Rear Diff and Axle" },
  {
    partNumber: "rear-tailight",
    keys: ["Object120", "Object121", "Object122"],
    label: "Rear Tailights",
  },
  { partNumber: "Backupperlight", keys: ["Backupperlight"], label: "Rear Upper Light" },
  { partNumber: "Tailgatetrim", keys: ["Tailgatetrim"], label: "Tailgate trim" },
  {
    partNumber: "rear-wiper",
    keys: ["Object126", "Object127"],
    label: "Rear Wiper",
  },
  { partNumber: "Rearwindow", keys: ["Rearwindow"], label: "Rear Window" },
  { partNumber: "Tailgate", keys: ["Tailgate"], label: "Tailgate" },
  { partNumber: "Bumpertrim", keys: ["Bumpertrim"], label: "Rear Bumper Trim" },
  { partNumber: "Rearbumper", keys: ["Rearbumper"], label: "Rear Bumper " },
  { partNumber: "Bumperlight", keys: ["Bumperlight"], label: "Rear Bumper Light" },
];
